name: Deploy to GitHub Pages (Minimal)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: List all files
      run: |
        echo "=== Root directory ==="
        ls -la
        echo "=== Public directory ==="
        ls -la public/
        echo "=== Checking index.html specifically ==="
        if [ -f "public/index.html" ]; then
          echo "index.html EXISTS"
          cat public/index.html
        else
          echo "index.html NOT FOUND"
        fi
        
    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
